// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import ProposalSubscriptionController from "./proposal_subscription_controller"
application.register("proposal-subscription", ProposalSubscriptionController)

import SlimSelectController from "./slim_select_controller"
application.register("slim-select", SlimSelectController)
